import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the AI-Native Technical Book on Physical AI & Humanoid Robotics
  bookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/lesson-1-1',
        'module-1/lesson-1-2',
        'module-1/lesson-1-3',
        'module-1/lesson-1-4',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/lesson-2-1',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: Advanced Robotics Control',
      items: [
        'module-3/lesson-3-1',
        'module-3/lesson-3-2',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: AI Integration in Robotics',
      items: [
        'module-4/lesson-4-1',
        'module-4/lesson-4-2',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Appendices',
      items: ['glossary', 'resources'],
      collapsed: true,
    },
  ],
};

export default sidebars;
